services:
  postgres:
    image: postgres:15.10
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iwvg_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devopsNet

volumes:
  postgres_data:
    name: "postgres-data"

networks:
  devopsNet:
    external: true