services:
  devops:
    build: .
    image: devops:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-server:5432/iwvg_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - devopsNet

networks:
  devopsNet:
    external: true