logging:
  level:
    root: WARN
    es.upm.api: INFO

# TODO: deactivate for final release
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  hosting: AWS

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PRODUCTION_DB_URL}
    username: ${PRODUCTION_DB_USER}
    password: ${PRODUCTION_DB_PASSWORD}
